package com.crs.denzip.model.constants;

public interface ScheduleStatusConstants {
  String SHORTLISTED = "SHORTLISTED";
  String SCHEDULING_REQUESTED = "SCHEDULING_REQUESTED";
  String SCHEDULED = "SCHEDULED";
  String VISITED = "VISITED";
  String ACCEPTED = "ACCEPTED";
  String REJECTED = "REJECTED";
  String ACTIVATED = "ACTIVATED";
  String DEACTIVATED = "DEACTIVATED";
  String PENDING_ACTIVATION = "PENDING_ACTIVATION";
  String SYSTEM_PENDING_DEACTIVATION = "SYSTEM_PENDING_DEACTIVATION";
  String SYSTEM_DEACTIVATED = "SYSTEM_DEACTIVATED";
  String PROSPECTIVE = "PROSPECTIVE";
}
